#!/bin/bash

# Run the build and deployment command, capture the output
output=$(suave-geth spell deploy ./Suciphus.sol:Suciphus 2>&1 | tee /dev/tty)

# Extract the deployed address from the output
deployed_address=$(echo "$output" | grep 'Contract deployed' | awk -F 'address=' '{print $2}')

# Check if the deployed_address is captured
if [ -z "$deployed_address" ]
then
    echo "Deployment failed or address not found."
    exit 1
else
    echo "Contract deployed to address: $deployed_address"
fi

# Get the ABI from the JSON file
abi=$(jq '.abi' ./out/Suciphus.sol/Suciphus.json)

# Check if the ABI is captured
if [ -z "$abi" ]
then
    echo "ABI not found."
    exit 1
else
    echo "ABI extracted successfully."
fi

mkdir -p src
cd src

# Write the address and ABI to suciphus.ts
echo "// generated by deploy.sh
import { Address } from \"viem\"

export const suciphus = {
  address: \"$deployed_address\" as Address,
  abi: $abi
}" > suciphus.ts

echo "Address and ABI written to /src/suciphus.ts"